/*
 * machines.js — which machines are being worked.
 *
 * The list lives in the Realtime Database, not in localStorage, because it is no
 * longer only a display preference: snorkel_worker reads it to decide whose
 * tasks to pick up. A machine added here is a machine the worker will work for,
 * which means the list has to be somewhere both the browser and the worker can
 * see.
 *
 * The *selection* stays local — which machine you happen to be looking at is
 * nobody else's business, and two people should be able to look at different
 * ones at the same time.
 *
 * A machine id is printed by the server and the worker on startup:
 *
 *   [server] machine id: goran-virtual-machine-70e3eec3
 */

import { get, onValue, ref, remove, set } from 'firebase/database';
import { rtdb } from './firebase';
import { DEFAULT_WORKSPACE, scoped, workspace } from './workspace';

const SELECTED_KEY = 'snorkel-bot-machine';
const LEGACY_KEY = 'snorkel-bot-machines';

/*
 * Scoped to this deployment. Two set-ups sharing one Firebase project would
 * otherwise share one machine list — each dashboard listing the other's
 * machines, and each worker picking up the other's tasks.
 */
export const machinesIndexPath = () => scoped('machines_index');

/** Where the list lived before workspaces existed. */
const LEGACY_INDEX = 'machines_index';

/**
 * Realtime Database keys cannot contain these. Machine ids generated by the
 * server never do, but this list is typed into by hand.
 */
const ILLEGAL = /[.$#[\]/]/;

export function validateMachineId(id) {
  const clean = String(id || '').trim();
  if (!clean) return { ok: false, error: 'Enter a machine id.' };
  if (ILLEGAL.test(clean)) {
    return { ok: false, error: 'A machine id cannot contain . $ # [ ] or /' };
  }
  if (clean.length > 128) return { ok: false, error: 'That is too long to be a machine id.' };
  return { ok: true, id: clean };
}

/**
 * Moves a pre-workspace machine list into the default workspace, once.
 *
 * Only ever runs for the default workspace, and only when it is empty and the
 * old path is not: a second deployment must never inherit the first one's
 * machines, and a list somebody has since emptied on purpose must not come
 * back. The old node is left alone rather than deleted, so a dashboard still
 * running the previous build keeps working.
 */
async function migrateLegacyIndex() {
  if (workspace() !== DEFAULT_WORKSPACE) return;
  try {
    const here = await get(ref(rtdb(), machinesIndexPath()));
    if (here.exists()) return;
    const legacy = await get(ref(rtdb(), LEGACY_INDEX));
    if (!legacy.exists()) return;

    const rows = {};
    legacy.forEach((child) => {
      // The workspace nodes are children of the same path, so anything that
      // looks like one is skipped rather than copied into itself.
      const value = child.val();
      if (value && typeof value === 'object' && !value.added_at) return;
      rows[child.key] = value;
    });
    if (!Object.keys(rows).length) return;

    await set(ref(rtdb(), machinesIndexPath()), rows);
    console.log(`[machines] moved ${Object.keys(rows).length} machine(s) into workspace "${workspace()}"`);
  } catch (err) {
    console.warn('[machines] could not move the old machine list:', err.message);
  }
}

/** Live list of machine ids, oldest first. Returns an unsubscribe function. */
export function watchMachines(onUpdate) {
  migrateLegacyIndex();
  return onValue(ref(rtdb(), machinesIndexPath()), (snapshot) => {
    const rows = [];
    snapshot.forEach((child) => {
      rows.push({ id: child.key, ...(child.val() || {}) });
    });
    rows.sort((a, b) => String(a.added_at || '').localeCompare(String(b.added_at || '')));
    onUpdate(rows.map((row) => row.id));
  });
}

export async function addMachine(id) {
  const check = validateMachineId(id);
  if (!check.ok) throw new Error(check.error);
  await set(ref(rtdb(), `${machinesIndexPath()}/${check.id}`), {
    added_at: new Date().toISOString(),
  });
  return check.id;
}

export async function removeMachine(id) {
  await remove(ref(rtdb(), `${machinesIndexPath()}/${id}`));
}

/**
 * Moves a list left in localStorage by an earlier version up into the database,
 * once. Without this, upgrading would silently empty the picker and — worse —
 * leave the worker with nothing to work on.
 */
export async function migrateLocalMachines() {
  if (typeof window === 'undefined') return 0;
  let legacy = [];
  try {
    const value = JSON.parse(window.localStorage.getItem(LEGACY_KEY) || '[]');
    legacy = Array.isArray(value) ? value.filter((id) => typeof id === 'string' && id) : [];
  } catch {
    return 0;
  }
  if (!legacy.length) return 0;

  for (const id of legacy) {
    const check = validateMachineId(id);
    if (check.ok) await set(ref(rtdb(), `${machinesIndexPath()}/${check.id}`), {
      added_at: new Date().toISOString(),
      migrated: true,
    });
  }
  window.localStorage.removeItem(LEGACY_KEY);
  return legacy.length;
}

export function getSelected() {
  if (typeof window === 'undefined') return '';
  return window.localStorage.getItem(SELECTED_KEY) || '';
}

export function setSelected(id) {
  if (typeof window === 'undefined') return;
  if (id) window.localStorage.setItem(SELECTED_KEY, id);
  else window.localStorage.removeItem(SELECTED_KEY);
}
